name: "Get Version"
description: "Gets a version from a 'csproj' or 'json' file."
inputs:
  version-file-path:
    description: "The path to the file containing the version value."
    required: true
  json-prop-path:
    description: "The JSON property path to the version value. Uses dot notation for nested properties."
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Setup Deno (v2.7.14)
      uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 #v2.0.4
      with:
        deno-version: v2.7.14
        cache: true

    - name: Run Script
      id: run-script
      shell: pwsh
      env:
        VERSION_FILE_PATH: "${{ inputs.version-file-path }}"
        JSON_PROP_PATH: "${{ inputs.json-prop-path }}"
      run: |
        $scriptFilePath = "$env:ACTION_PATH/get-version.ts";

        deno run -ERW $scriptFilePath;
outputs:
  version:
    description: "The extracted version."
    value: ${{ steps.run-script.outputs.version }}
