name: "Send X Release Announcement"
description: "Sends a release announcement to X"
inputs:
  repo-owner:
    description: "The owner of the repository."
    required: true
  repo-name:
    description: "The name of the repository."
    required: true
  version:
    description: "The version of the release."
    required: true
  website-url:
    description: "The URL of a website to include in the post."
    required: false
  github-token:
    description: "The GitHub token used to download the script for installation."
    required: true
  release-x-post-template-repo-name:
    description: "The name of the repository containing the release X post template."
    required: true
  release-x-post-template-branch-name:
    description: "The branch name of the repository containing the release X post template."
    required: true
  relative-release-x-post-template-file-path:
    description: "The relative file path to the release X post template within the repository."
    required: true
  discord-invite-code:
    description: "The Discord invite code to include in the post."
    required: true
  x-broadcast-enabled:
    description: "Whether to broadcast the post on X."
    required: true
  x-access-token-key:
    description: "The X access token key."
    required: true
  x-access-token-secret:
    description: "The X access token secret."
    required: true
  x-consumer-api-key:
    description: "The X consumer API key."
    required: true
  x-consumer-api-secret:
    description: "The X consumer API secret."
    required: true
  deno-version:
    description: "The version of Deno to use."
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Deno (${{ inputs.deno-version }})
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ inputs.deno-version }}
        cache: true

    - name: Run Script
      shell: pwsh
      env:
        GITHUB_TOKEN: "${{ inputs.github-token }}"
        DENO_AUTH_TOKENS: "${{ inputs.github-token }}@raw.githubusercontent.com"
        REPO_OWNER: "${{ inputs.repo-owner }}"
        REPO_NAME: "${{ inputs.repo-name }}"
        VERSION: "${{ inputs.version }}"
        WEBSITE_URL: "${{ inputs.website-url }}"
        RELEASE_X_POST_TEMPLATE_REPO_NAME: "${{ inputs.release-x-post-template-repo-name }}"
        RELEASE_X_POST_TEMPLATE_BRANCH_NAME: "${{ inputs.release-x-post-template-branch-name }}"
        RELATIVE_RELEASE_X_POST_TEMPLATE_FILE_PATH: "${{ inputs.relative-release-x-post-template-file-path }}"
        DISCORD_INVITE_CODE: "${{ inputs.discord-invite-code }}"
        X_BROADCAST_ENABLED: "${{ inputs.x-broadcast-enabled }}"
        X_ACCESS_TOKEN_KEY: "${{ inputs.x-access-token-key }}"
        X_ACCESS_TOKEN_SECRET: "${{ inputs.x-access-token-secret }}"
        X_CONSUMER_API_KEY: "${{ inputs.x-consumer-api-key }}"
        X_CONSUMER_API_SECRET: "${{ inputs.x-consumer-api-secret }}"
      run: |
        $scriptFilePath = "${{ github.action_path }}/send-x-release-announcement.ts";

        deno run -EN $scriptFilePath;
