name: "Close Milestone"
description: "Closes a milestone for a GitHub repository"
inputs:
  repo-owner:
    description: "The owner of the repository."
    required: true
  repo-name:
    description: "The name of the repository."
    required: true
  milestone-title:
    description: "The title of the milestone to close."
    required: true
  github-token:
    description: "The GitHub token used to authenticate API requests."
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Deno (v2.7.14)
      uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 #v2.0.4
      with:
        deno-version: v2.7.14
        cache: true

    - name: Run Script
      shell: pwsh
      env:
        REPO_OWNER: "${{ inputs.repo-owner }}"
        REPO_NAME: "${{ inputs.repo-name }}"
        MILESTONE_TITLE: "${{ inputs.milestone-title }}"
        GITHUB_TOKEN: "${{ inputs.github-token }}"
        DENO_AUTH_TOKENS: "${{ inputs.github-token }}@raw.githubusercontent.com"
      run: |
        $scriptFilePath = "$env:ACTION_PATH/close-milestone.ts";

        deno run -ERN $scriptFilePath;
