name: "Release Notes Exist"
description: "Checks if a release notes file exists."
inputs:
  release-notes-file-path:
    description: "The fully qualified file path to the release notes file."
    required: true
  fail-if-does-not-exist:
    description: "Fail if the release notes do not exist."
    required: false
    default: "true"
  cache-enabled:
    description: "Whether to enable caching of the Deno installation."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Setup Deno (v2.7.14)
      uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 #v2.0.4
      with:
        deno-version: v2.7.14
        cache: ${{ inputs.cache-enabled == 'true' }}

    - name: Run Script
      id: run-script
      shell: pwsh
      env:
        RELEASE_NOTES_FILE_PATH: "${{ inputs.release-notes-file-path }}"
        FAIL_IF_DOES_NOT_EXIST: "${{ inputs.fail-if-does-not-exist }}"
        GITHUB_TOKEN: "${{ inputs.github-token }}"
      run: |
        $scriptFilePath = "$env:GITHUB_ACTION_PATH/release-notes-exist.ts";

        deno run -ERWN $scriptFilePath;
outputs:
  release-notes-exist:
    description: "Whether the release notes exist."
    value: ${{ steps.run-script.outputs.release-notes-exist }}
