name: "Nuget Package Exists"
description: "Checks if a NuGet package exists."
inputs:
  nuget-pkg-name:
    description: "The name of the NuGet package to check."
    required: true
  nuget-pkg-version:
    description: "The version of the NuGet package to check."
    required: true
  fail-if-exists:
    description: "Fail if the NuGet package exists."
    required: false
    default: "true"
  cache-enabled:
    description: "Whether to enable caching of the Deno installation."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Setup Deno (v2.7.14)
      uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed #v2.0.5
      with:
        deno-version: v2.7.14
        cache: ${{ inputs.cache-enabled == 'true' }}

    - name: Run Script
      id: run-script
      shell: pwsh
      env:
        NUGET_PKG_NAME: "${{ inputs.nuget-pkg-name }}"
        NUGET_PKG_VERSION: "${{ inputs.nuget-pkg-version }}"
        FAIL_IF_EXISTS: "${{ inputs.fail-if-exists }}"
      run: |
        $scriptFilePath = "$env:GITHUB_ACTION_PATH/nuget-pkg-exists.ts";

        deno run -ERWN $scriptFilePath;
outputs:
  package-exists:
    description: "Whether the NuGet package exists."
    value: ${{ steps.run-script.outputs.package-exists }}
