name: 🚧 Project Item
description: Create an issue for the project (Project maintainers only).
title: "🚧"
projects: ["KinsonDigital/11"]
body:
- type: checkboxes
  attributes:
    label: Complete The Item Below
    options:
    - label: I have updated the title without removing the 🚧 emoji.
      required: true

- type: textarea
  attributes:
    label: Description
    description: A description of the feature and/or change.
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    placeholder: |
      Example:
        - [ ] Item 1 complete
        - [ ] Item 2 complete
    description: The items to complete in order to satisfy the Definition of Done.
  validations:
    required: true
    render: markdown

- type: checkboxes
  attributes:
    label: ToDo Items
    description: Complete the following items before requesting a PR review.
    options:
    - label: Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
    - label: Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
    - label: Issue linked to the correct milestone _(if applicable)_.

- type: textarea
  attributes:
    label: Issue Dependencies
    placeholder: |
      Example:
        - #10
        - #20
    description: |
      A list of issues that are dependencies of this issue and need to be completed first.
  validations:
    required: false

- type: textarea
  attributes:
    label: Related Work
    placeholder: |
      Example:
        - #10 
        - #20
    description: |
      A list of issues related to this issue but are not a dependency.
  validations:
    required: false

- type: textarea
  attributes:
    label: "Additional Information:"
    description: DO NOT CHANGE ANYTHING BELOW!!
    value: |
      **_<details closed><summary>Change Type Labels</summary>_**
      
      | Change Type         | Label                |
      |---------------------|----------------------|
      | Bug Fixes           | `🐛bug` |
      | Breaking Changes    | `🧨breaking changes` |
      | New Feature         | `✨new feature` |
      | CICD Changes        | `♻️cicd` |
      | Config Changes      | `⚙️config` |
      | Code Doc Changes    | `🗒️documentation/code` |
      | Product Doc Changes | `📝documentation/product` |
      </details>

      **_<details closed><summary>Priority Type Labels</summary>_**
      
      | Priority Type       | Label             |
      |---------------------|-------------------|
      | Low Priority        | `low priority`    |
      | Medium Priority     | `medium priority` |
      | High Priority       | `high priority`   |
      </details>

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/KinsonDigital/.github/blob/main/docs/CODE_OF_CONDUCT.md).
    options:
      - label: I agree to follow this project's Code of Conduct.
        required: true
