name: 🚧 Project Item
description: Create an issue for a project.  (Project maintainers only)
title: "🚧"
body:
- type: checkboxes
  attributes:
    label: I have done the items below . . .
    description: Please make sure to do the items below.
    options:
    - label: I have updated the title without removing the 🚧 emoji.
      required: true

- type: textarea
  attributes:
    label: Description
    description: A description of the feature and/or change from the user's perspective.
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: |
      The list of items that need to be completed to satisfy the definition of done.
    value: |
      **This issue is finished when:**
      - [ ] Unit tests added
      - [ ] All unit tests pass
  validations:
    required: true
    render: markdown

- type: checkboxes
  attributes:
    label: ToDo Items
    description: Complete the following items before requesting a PR review.
    options:
    - label: Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
    - label: Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
    - label: Issue linked to the correct project.
    - label: Issue linked to the correct milestone.
    - label: Draft pull request created and linked to this issue.

- type: textarea
  attributes:
    label: Issue Dependencies
    placeholder: |
      No Issue Dependencies Added.
      Example:
        - #10 Create new class
        - #20 Add unit tests to service
        - #30 Cleanup code in UI
    description: |
      A list of issues that are dependencies of this issue and need to be finished first.
      Use the '#\<issue-number\>' syntax to link an issue.
  validations:
    required: false

- type: textarea
  attributes:
    label: Related Work
    placeholder: |
      No Related Work Items Added.
      Example:
        - #10 Create new class
        - #20 Add unit tests to service
        - #30 Cleanup code in UI
    description: |
      A list of issues related to this issue but are not a dependency.
      Use the '#\<issue-number\>' syntax to link an issue.
  validations:
    required: false

- type: textarea
  attributes:
    label: "Additional Information:"
    description: DO NOT CHANGE ANYTHING BELOW!!
    value: |
      **_<details closed><summary>Change Type Labels</summary>_**
      
      | Change Type         | Label                                                                                |
      |---------------------|--------------------------------------------------------------------------------------|
      | Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
      | Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
      | Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
      | Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
      | Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
      | Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
      </details>

      **_<details closed><summary>Priority Type Labels</summary>_**
      
      | Priority Type       | Label                                                              |
      |---------------------|--------------------------------------------------------------------|
      | Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
      | Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
      | High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
      </details>

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](../../code_of_conduct.md).
    options:
      - label: I agree to follow this project's Code of Conduct.
        required: true
