name: 🚧 Project Item
description: Create an issue for the project (Project maintainers only).
projects: ["KinsonDigital/11"]
body:
- type: checkboxes
  attributes:
    label: Complete The Item Below
    options:
    - label: I have updated the title without removing the 🚧 emoji.
      required: true

- type: textarea
  attributes:
    label: Description
    description: A description of the feature and/or change.
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete to satisfy the Definition of Done.
    value: |
      ### The items to complete to satisfy the Definition of Done.
      - [ ] All the unit tests have been executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: ToDo Items
    description: Complete the following items before requesting a PR review.
    value: |
      ### The items to complete to satisfy the Definition of Done.
      - [ ] Add a priority label to the issue. Refer to the _**Priority Type Labels**_ section below.
      - [ ] Link the issue to the correct milestone _(if applicable)_.

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/KinsonDigital/.github/blob/main/docs/CODE_OF_CONDUCT.md).
    options:
      - label: I agree to follow this project's Code of Conduct.
        required: true
