name: "Rename Milestone"
description: "Renames a milestone for a GitHub repository"
inputs:
  repo-owner:
    description: "The owner of the repository."
    required: true
  repo-name:
    description: "The name of the repository."
    required: true
  current-milestone-name:
    description: "The current name of the milestone to rename."
    required: true
  new-milestone-name:
    description: "The new name for the milestone."
    required: true
  github-token:
    description: "The GitHub token used to authenticate API requests."
    required: true
  cache-enabled:
    description: "Whether to enable caching of the Deno installation."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Setup Deno (v2.7.14)
      uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed #v2.0.5
      with:
        deno-version: v2.7.14
        cache: ${{ inputs.cache-enabled == 'true' }}

    - name: Run Script
      shell: pwsh
      env:
        REPO_OWNER: "${{ inputs.repo-owner }}"
        REPO_NAME: "${{ inputs.repo-name }}"
        CURRENT_MILESTONE_NAME: "${{ inputs.current-milestone-name }}"
        NEW_MILESTONE_NAME: "${{ inputs.new-milestone-name }}"
        GITHUB_TOKEN: "${{ inputs.github-token }}"
        DENO_AUTH_TOKENS: "${{ inputs.github-token }}@raw.githubusercontent.com"
      run: |
        $scriptFilePath = "$env:GITHUB_ACTION_PATH/rename-milestone.ts";

        deno run -ERN $scriptFilePath;
