name: "Validate Version"
description: "Validates a version."
inputs:
  version:
    description: "The version being released."
    required: true
  release-type:
    description: "The type of release.  Either 'Preview' or 'Production'."
    required: true
  deno-version:
    description: "The version of Deno to use."
    required: true
  action-version:
    description: "The version of this action to use."
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Deno (${{ inputs.deno-version }})
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ inputs.deno-version }}

    - name: Run Script
      shell: pwsh
      env:
        VERSION: "${{ inputs.VERSION }}"
        RELEASE_TYPE: "${{ inputs.release-type }}"
      run: |
        $baseUrl = "https://raw.githubusercontent.com";
        $version = "${{ inputs.action-version }}";
        $fileName = "validate-version.ts";
        $path = "EngagedAgility/Infrastructure/refs/tags/$version/actions/validate-version/$fileName";
        $scriptUrl = "$baseUrl/$path";

        deno run -E $scriptUrl;
