name: "Validate Version"
description: "Validates a version."
inputs:
  version:
    description: "The version being released."
    required: true
  release-type:
    description: "The type of release.  Either 'Preview' or 'Production'."
    required: true
  strip-v-prefix:
    description: |
      Whether to strip the 'v' prefix from the version.
      If 'false', the version will be prefixed with 'v' if it does not already have it.
    required: false
    default: "false"
  cache-enabled:
    description: "Whether to enable caching of the Deno installation."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Setup Deno (v2.7.14)
      uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed #v2.0.5
      with:
        deno-version: v2.7.14
        cache: ${{ inputs.cache-enabled == 'true' }}

    - name: Run Script
      shell: pwsh
      env:
        VERSION: "${{ inputs.VERSION }}"
        STRIP_V_PREFIX: "${{ inputs.strip-v-prefix }}"
        RELEASE_TYPE: "${{ inputs.release-type }}"
      run: |
        $scriptFilePath = "$env:GITHUB_ACTION_PATH/validate-version.ts";

        deno run -E $scriptFilePath;
