name: "Update Copyright"
description: "Updates the copyright information in a 'csproj' file."
inputs:
  cs-proj-file-name:
    description: "The name of the 'csproj' file to update."
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Deno (v2.7.14)
      uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 #v2.0.4
      with:
        deno-version: v2.7.14
        cache: true

    - name: Run Script
      shell: pwsh
      env:
        CS_PROJ_FILE_NAME: "${{ inputs.cs-proj-file-name }}"
      run: |
        $scriptFilePath = "${{ github.action_path }}/update-copyright.ts";

        deno run -ERW $scriptFilePath;
