name: "Transpile README"
description: "Transpiles HTML in a README.md file to markdown."
inputs:
  base-dir-path:
    description: "The base directory path to use."
    required: true
  cache-enabled:
    description: "Whether to enable caching of the Deno installation."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

    - name: Setup Deno (v2.7.14)
      uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed #v2.0.5
      with:
        deno-version: v2.7.14
        cache: ${{ inputs.cache-enabled == 'true' }}

    - name: Run Script
      shell: pwsh
      env:
        BASE_DIR_PATH: "${{ inputs.base-dir-path }}"
        JSON_PROP_PATH: "${{ inputs.json-prop-path }}"
      run: |
        $scriptFilePath = "$env:GITHUB_ACTION_PATH/transpile-readme.ts";

        deno run -ERW $scriptFilePath;
