name: "Transpile README"
description: "Transpiles HTML in a README.md file to markdown."
inputs:
  base-dir-path:
    description: "The base directory path to use."
    required: true
  deno-version:
    description: "The version of Deno to use."
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Setup Deno (${{ inputs.deno-version }})
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ inputs.deno-version }}

    - name: Run Script
      shell: pwsh
      env:
        BASE_DIR_PATH: "${{ inputs.base-dir-path }}"
        JSON_PROP_PATH: "${{ inputs.json-prop-path }}"
      run: |
        $scriptFilePath = "${{ github.action_path }}/transpile-readme.ts";

        deno run -ERW $scriptFilePath;
