name: "Transpile README"
description: "Transpiles HTML in a README.md file to markdown."
inputs:
  base-dir-path:
    description: "The base directory path to use."
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Setup Deno (v2.7.14)
      uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 #v2.0.4
      with:
        deno-version: v2.7.14
        cache: true

    - name: Run Script
      shell: pwsh
      env:
        BASE_DIR_PATH: "${{ inputs.base-dir-path }}"
        JSON_PROP_PATH: "${{ inputs.json-prop-path }}"
      run: |
        $scriptFilePath = "${{ github.action_path }}/transpile-readme.ts";

        deno run -ERW $scriptFilePath;
