name: "Validate .NET SDK Versions"
description: "Checks if the all of the .NET SDK versions for all projects in the repository exist and match a specified version."
inputs:
  base-search-dir-path:
    description: "The base directory path to search for .NET projects."
    required: true
  net-sdk-version:
    description: "The .NET SDK version to validate against."
    required: true
  cache-enabled:
    description: "Whether to enable caching of the Deno installation."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

    - name: Setup Deno (v2.9.x)
      uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed #v2.0.5
      with:
        deno-version: v2.9.x
        cache: ${{ inputs.cache-enabled == 'true' }}

    - name: Run Script
      id: run-script
      shell: pwsh
      env:
        BASE_SEARCH_DIR_PATH: "${{ inputs.base-search-dir-path }}"
        NET_SDK_VERSION: "${{ inputs.net-sdk-version }}"
      run: |
        $scriptFilePath = "$env:GITHUB_ACTION_PATH/validate-sdk-versions.ts";

        deno run -ER $scriptFilePath;
