name: "Validate .NET SDK Versions"
description: "Checks if the all of the .NET SDK versions for all projects in the repository exist and match a specified version."
inputs:
  base-search-dir-path:
    description: "The base directory path to search for .NET projects."
    required: true
  net-sdk-version:
    description: "The .NET SDK version to validate against."
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Setup Deno (v2.7.14)
      uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 #v2.0.4
      with:
        deno-version: v2.7.14
        cache: true

    - name: Run Script
      id: run-script
      shell: pwsh
      env:
        BASE_SEARCH_DIR_PATH: "${{ inputs.base-search-dir-path }}"
        NET_SDK_VERSION: "${{ inputs.net-sdk-version }}"
      run: |
        $scriptFilePath = "$env:ACTION_PATH/validate-sdk-versions.ts";

        deno run -ER $scriptFilePath;
