name: "JSR Package Exists"
description: "Checks if a JSR package exists."
inputs:
  scope:
    description: "The scope of the JSR package."
    required: true
  pkg-name:
    description: "The name of the JSR package to check."
    required: true
  version:
    description: "The version of the JSR package to check."
    required: true
  fail-if-exists:
    description: "Fail if the JSR package exists."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Setup Deno (v2.7.14)
      uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 #v2.0.4
      with:
        deno-version: v2.7.14
        cache: true

    - name: Run Script
      id: run-script
      shell: pwsh
      env:
        SCOPE: "${{ inputs.scope }}"
        PKG_NAME: "${{ inputs.pkg-name }}"
        VERSION: "${{ inputs.version }}"
        FAIL_IF_EXISTS: "${{ inputs.fail-if-exists }}"
      run: |
        $scriptFilePath = "$env:ACTION_PATH/jsr-pkg-exists.ts";

        deno run -ERWN $scriptFilePath;
outputs:
  package-exists:
    description: "Whether the JSR package exists."
    value: ${{ steps.run-script.outputs.package-exists }}
