name: "Send Bluesky Release Announcement"
description: "Sends a release announcement to Bluesky"
inputs:
  repo-owner:
    description: "The owner of the repository."
    required: true
  project-name:
    description: "The name of the project."
    required: false
  version:
    description: "The version of the release."
    required: true
  website-url:
    description: "The URL of a website to include in the post."
    required: false
  github-token:
    description: "The GitHub token used to download the script for installation."
    required: true
  post-template-repo-name:
    description: |
      The name of the repository containing the release Bluesky post template.
      This input requires the use of the 'post-template-branch-name' and 'post-template-repo-relative-file-path' inputs.
      Using the 'local-post-template-file-path' input takes precedence over this input.
    required: false
  post-template-branch-name:
    description: |
      The branch name of the repository containing the release Bluesky post template.
      This input requires the use of the 'post-template-repo-name' and 'post-template-repo-relative-file-path' inputs.
      Using the 'local-post-template-file-path' input takes precedence over this input.
    required: false
  post-template-repo-relative-file-path:
    description: |
      The relative file path to the release Bluesky post template within the repository set by
      the 'post-template-repo-name' and 'post-template-branch-name' inputs. This input
      requires the use of the 'post-template-repo-name' and 'post-template-branch-name' inputs.
      Using the 'local-post-template-file-path' input takes precedence over this input.
    required: false
  local-post-template-file-path:
    description: |
      The file path to the release Bluesky post template within the checked-out repository, relative to the GitHub Actions workspace.
      The caller must check out the repository (for example, using 'actions/checkout') before using this input.
      This input takes precedence over the 'post-template-repo-name', 'post-template-branch-name', and 'post-template-repo-relative-file-path' inputs.
    required: false
  discord-invite-code:
    description: "The Discord invite code to include in the post."
    required: false
  service:
    description: "The Bluesky service URL."
    required: true
  identifier:
    description: "The Bluesky identifier."
    required: true
  password:
    description: "The Bluesky password."
    required: true
  deno-version:
    description: "The version of Deno to use."
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Deno (${{ inputs.deno-version }})
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ inputs.deno-version }}
        cache: true

    - name: Run Script
      shell: pwsh
      env:
        GITHUB_TOKEN: "${{ inputs.github-token }}"
        DENO_AUTH_TOKENS: "${{ inputs.github-token }}@raw.githubusercontent.com"
        OWNER_NAME: "${{ inputs.repo-owner }}"
        PROJECT_NAME: "${{ inputs.project-name }}"
        VERSION: "${{ inputs.version }}"
        WEBSITE_URL: "${{ inputs.website-url }}"
        POST_TEMPLATE_REPO_NAME: "${{ inputs.post-template-repo-name }}"
        POST_TEMPLATE_BRANCH_NAME: "${{ inputs.post-template-branch-name }}"
        POST_TEMPLATE_REPO_RELATIVE_FILE_PATH: "${{ inputs.post-template-repo-relative-file-path }}"
        LOCAL_POST_TEMPLATE_FILE_PATH: "${{ inputs.local-post-template-file-path }}"
        DISCORD_INVITE_CODE: "${{ inputs.discord-invite-code }}"
        SERVICE: "${{ inputs.service }}"
        IDENTIFIER: "${{ inputs.identifier }}"
        PASSWORD: "${{ inputs.password }}"
      run: |
        $scriptFilePath = "${{ github.action_path }}/send-bluesky-release-announcement.ts";

        deno run -ERN $scriptFilePath;
