name: Unit C# Tests


defaults:
  run:
    shell: pwsh
  
  
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        description: "The name of the C# project to validate."
        type: string
      build-config:
        required: true
        description: The build configuration to use (e.g. 'Debug', 'Release').
        type: string
      net-sdk-version:
        required: true
        description: The .NET SDK version to use (e.g. '7.0.x').
        type: string
      base-path:
        required: false
        description: The base directory path to start the search.
        type: string
      runs-on:
        required: false
        description: The type of machine to run the job on.
        type: string
        default: ubuntu-latest


jobs:
  resolve_proj_file_path:
    name: Resolving ${{ inputs.project-name }} Project File Path
    uses: KinsonDigital/Infrastructure/.github/workflows/reusable/resolve-csharp-proj-file.yml@v9.0.0
    with:
      project-name: ${{ inputs.project-name }}
      base-path: ${{ inputs.base-path }}


  run_unit_tests:
    name: Run Unit Tests
    needs: resolve_proj_file_path
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.net-sdk-version }}

      - name: Restore Dependencies
        run: dotnet restore "${{ needs.resolve_proj_file_path.outputs.project-file-path }}"

      - name: Execute Unit Tests
        run: dotnet build "${{ needs.resolve_proj_file_path.outputs.project-file-path }}" `
          -c ${{ inputs.build-config }} `
          --no-restore
