@issue_number = 23

# Get Issue

GET {{hostAddress}}/repos/{{repoOwner}}/{{repoName}}/issues/{{$processEnv %GITHUB_REST_API}}

###

# Get All Milestone Issues & Pull Requests

GET {{hostAddress}}/repos/{{repoOwner}}/{{repoName}}/issues?milestone={{milestoneNumber}}&state=all

