## Docs: https://github.com/Huachao/vscode-restclient#environment-variables

@issue_number = 23
@pr_number = 222
@pushEvent = push
@prEvent = pull_request


# Get Issue

GET {{hostAddress}}/repos/{{repoOwner}}/{{repoName}}/issues/{{issue_number}}

###

# Get All Milestone Issues & Pull Requests

GET {{hostAddress}}/repos/{{repoOwner}}/{{repoName}}/issues?milestone={{milestoneNumber}}&state=all

###

# Get Pull Request
GET {{hostAddress}}/repos/{{repoOwner}}/{{repoName}}/pulls/{{pr_number}}

###

# Get All Releases
GET {{hostAddress}}/repos/{{repoOwner}}/{{repoName}}/releases

###

# Get Completed Workflow Runs With Push Events
GET  {{hostAddress}}/repos/{{repoOwner}}/{{repoName}}/actions/runs?event={{pushEvent}}&status=completed&page=1&per_page=100

###

# Get Completed Workflow Runs With Pull Request Events
GET  {{hostAddress}}/repos/{{repoOwner}}/{{repoName}}/actions/runs?event={{prEvent}}&status=completed&page=1&per_page=10

###

# Get Failed Workflow Runs

GET  {{hostAddress}}/repos/{{repoOwner}}/{{repoName}}/actions/runs?status=failure&page=1&per_page=10
