name: ✔Build Status Check


on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      build-config:
        required: true
        type: string
      net-sdk-version:
        required: true
        type: string
      base-path:
        required: false
        type: string


jobs:
  build_project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Resolve Project File Path
      id: resolve-file-path
      shell: pwsh
      run: |
        $basePath = !$basePath -or $basePath -eq "" ? "${{ github.workspace }}" : $basePath;

        $result = Get-ChildItem -Path "$basePath/**/${{ inputs.project-name }}.csproj" -Recurse | ForEach-Object{$_.FullName};

        $resultType = $result ? $result.GetType().Name : $null;

        # If null, no project file was found
        if (!$result) {
            Write-Host "::error::Project file not found";
            exit 1; # Fail Workflow
        } elseif ($resultType -ne "String") {
            Write-Host "::error::Found too many project files!!";

            foreach ($item in $result) {
                Write-Host "`t$item";
            }

            exit 1; # Fail Workflow
        } else {
            Write-Host "::set-output name=project-file-path::$result";
        }

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.net-sdk-version }}

    - name: Restore Dependencies
      run: dotnet restore "${{ steps.resolve-file-path.outputs.project-file-path }}"

    - name: Build Project
      run: dotnet build "${{ steps.resolve-file-path.outputs.project-file-path }}" `
        -c ${{ inputs.build-config }} `
        --no-restore
