name: Build C# Project


defaults:
  run:
    shell: pwsh
  
  
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        description: The name of the C# project to validate
        type: string
      build-config:
        required: true
        description: The build configuration to use (e.g. 'Debug', 'Release')
        type: string
      net-sdk-version:
        required: true
        description: The .NET SDK version to use (e.g. '7.0.x')
        type: string
      base-path:
        required: false
        description: The base directory path to start the search from
        type: string


jobs:
  build_project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Resolve Project File Path
        id: resolve-file-path
        run: |
          $basePath = !$basePath -or $basePath -eq "" ? "${{ github.workspace }}" : $basePath;

          $result = Get-ChildItem -Path "$basePath/**/${{ inputs.project-name }}.csproj" -Recurse | ForEach-Object{$_.FullName};

          $resultType = $result ? $result.GetType().Name : $null;

          # If null, no project file was found
          if (!$result) {
            Write-Host "::error::Project file not found";
            exit 1; # Fail Workflow
          } elseif ($resultType -ne "String") {
            Write-Host "::error::Found too many project files!!";

            foreach ($item in $result) {
                Write-Host "`t$item";
            }

            exit 1; # Fail Workflow
          } else {
            "project-file-path=$result" >> $env.GITHUB_OUTPUT;
          }

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.net-sdk-version }}

      - name: Restore Dependencies
        run: dotnet restore "${{ steps.resolve-file-path.outputs.project-file-path }}"

      - name: Build Project
        run: dotnet build "${{ steps.resolve-file-path.outputs.project-file-path }}" `
          -c ${{ inputs.build-config }} `
          --no-restore
