name: ⚙️ Perform DotNet Lib Release
run-name: ⚙️ Perform ${{ inputs.release-type }} Release (${{ inputs.build-config }} Build)


permissions:
  contents: write


defaults:
  run:
    shell: pwsh


on:
  workflow_call:
    inputs:
      project-name:
        description: "The name of the C# project."
        required: true
        type: string
      owner-name:
        description: "The owner of the GitHub repository."
        required: true
        type: string
      repo-name:
        description: "The name of the GitHub repository."
        required: true
        type: string
      release-type:
        description: "The type of release to perform.  Either 'Preview' or 'Production'."
        required: true
        type: string
      version:
        description: "The application/library version."
        required: true
        type: string
      net-sdk-version:
        description: "The version of the .NET SDK to use."
        required: true
        type: string
      relative-release-notes-file-path:
        description: "The file path to the release notes file relative to the root of the project."
        required: true
        type: string
      build-config:
        description: "The build configuration to use. This is either 'Debug' or 'Release'."
        required: true
        type: string
      telemetry-enabled:
        description: "If true, enables telemetry for the dotnet library."
        required: false
        default: false
        type: boolean
      transpile-readme:
        description: "If true, transpiles the README.md file HTML to markdown."
        required: false
        default: false
        type: boolean
      dry-run:
        description: |
          "Runs a dry run of this workflow without publishing the nuget package, creating a github release"
        required: false
        type: boolean
    secrets:
      cicd-pat:
        required: true
        description: The CICD personal access token.
      nuget-api-key:
        required: true
        description: "The nuget API key used for authenticating with nuget.org to push packages."
      telemetry-key:
        required: false
        description: The telemetry key to use if telemetry is enabled.


jobs:
  perform_release:
    name: Perform ${{ inputs.release-type }} Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Infrastructure Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          repository: KinsonDigital/Infrastructure
          ref: main

      - name: Checkout Caller Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          repository: ${{ inputs.owner-name }}/${{ inputs.repo-name }}
          path: "${{ inputs.repo-name }}-4e2c95f5"

      - name: Set Up .NET SDK
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 #v5.2.0
        with:
          dotnet-version: "${{ inputs.net-sdk-version }}"

      - name: Set Up NuGet
        uses: NuGet/setup-nuget@fd55a6f3b34392fa83fde1454582407d8c714123 #v4.0.0

      - name: Set Up Deno (v2.9.x)
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed #v2.0.5
        with:
          deno-version: v2.9.x

      - name: Transpile README
        if: inputs.transpile-readme == true
        uses: ./actions/transpile-readme
        with:
          base-dir-path: "${{ github.workspace }}/${{ inputs.repo-name }}-4e2c95f5"

      - name: Update Copyright
        uses: ./actions/update-copyright
        with:
          cs-proj-file-name: "${{ inputs.project-name }}.csproj"

      - name: Create NuGet Package
        env:
          PROJECT_NAME: "${{ inputs.project-name }}"
          BUILD_CONFIG: "${{ inputs.build-config }}"
          BASE_DIR_PATH: "${{ github.workspace }}/${{ inputs.repo-name }}-4e2c95f5"
          TELEMETRY_ENABLED: "${{ inputs.telemetry-enabled }}"
          TELEMETRY_KEY: "${{ secrets.telemetry-key }}"
        run: |
          dotnet pack `
            "$env:BASE_DIR_PATH/${env:PROJECT_NAME}/${env:PROJECT_NAME}.csproj" `
            -o "$env:BASE_DIR_PATH" `
            -c ${env:BUILD_CONFIG} `
            -p:IncludeSymbols=true `
            -p:SymbolPackageFormat=snupkg `
            -p:EnableTelemetry="$env:TELEMETRY_ENABLED" `
            -p:TelemetryKey="$env:TELEMETRY_KEY";

      - name: Publish NuGet Package
        if: ${{ inputs.dry-run == false }}
        env:
          PROJECT_NAME: "${{ inputs.project-name }}"
          ORG_NAME: "${{ vars.ORGANIZATION_NAME }}"
          VERSION: "${{ inputs.version }}"
          NUGET_API_KEY: "${{ secrets.nuget-api-key }}"
          BASE_DIR_PATH: "${{ github.workspace }}/${{ inputs.repo-name }}-4e2c95f5"
        run: |
          $version = "$env:VERSION";
          $version = $version.StartsWith("v") ? $version.Substring(1) : $version;

          # Push the nuget package
          dotnet nuget push `
            "$env:BASE_DIR_PATH/$env:ORG_NAME.$env:PROJECT_NAME.$version.nupkg" `
            --api-key $env:NUGET_API_KEY `
            --source https://api.nuget.org/v3/index.json;

      - name: Create GitHub Release
        if: ${{ inputs.dry-run == false }}
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          name: "🚀${{ inputs.release-type }} - ${{ inputs.version }}"
          tag: ${{ inputs.version }}
          owner: ${{ vars.ORGANIZATION_NAME }}
          repo: ${{ inputs.repo-name }}
          bodyFile: "${{ inputs.repo-name }}-4e2c95f5/${{ inputs.relative-release-notes-file-path }}"
          prerelease: ${{ inputs.release-type }} == 'Preview'
          token: ${{ secrets.cicd-pat }}
