name: ✅Issue PR Sync Bot


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:
  pull_request:
    branches: [master, preview]
  issues:
    types: [edited]


jobs:
  issue_pr_sync_bot:
    name: Issue PR Sync Bot
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Bot
        run: |
          $scriptUrl = "${{ vars.SCRIPT_BASE_URL }}/${{ vars.CICD_SCRIPTS_VERSION }}/${{ vars.SCRIPT_RELATIVE_DIR_PATH}}/in-sync-status-check.ts";

          deno run `
            --allow-net `
            "$scriptUrl" `
            "${{ vars.PROJECT_NAME }}" `
            "${{ vars.DEFAULT_PR_REVIEWER }}" `
            "${{ github.event.pull_request.number }}" `
            "${{ secrets.CICD_REST_API }}";
