name: 🤖Issue PR Sync Bot


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:
  issues:
    types: [edited]


jobs:
  issue_pr_sync_bot:
    name: Issue PR Sync Bot
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Bot
        run: |
          $issueData = "${{ toJson(github.event.issue) }}";
          $scriptUrl = "${{ vars.SCRIPT_BASE_URL }}/${{ vars.CICD_SCRIPTS_VERSION }}/${{ vars.SCRIPT_RELATIVE_DIR_PATH}}/update-pr-sync-status.ts";

          deno run `
            --allow-net `
            "$scriptUrl" `
            "${{ vars.PROJECT_NAME }}" `
            "$issueData" `
            "${{ secrets.CICD_REST_API }}";
