name: ✅Lint Status Check


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    branches: [main, preview]


jobs:
  lint_status_check:
    name: Lint Status Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Set Up Deno (${{ vars.DENO_VERSION }})
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 #v2.0.4
        with:
          deno-version: ${{ vars.DENO_VERSION }}

      - name: Run Linting
        run: deno lint
