name: ✅Lint Status Check


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    branches: main


jobs:
  lint_status_check:
    name: Lint Status Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{  vars.DENO_VERSION }}

      - name: Run Linting
        run: deno lint
