name: Check NuGet Package
run-name: Check NuGet Package (${{ inputs.version }})


defaults:
  run:
    shell: pwsh


on:
  workflow_call:
    inputs:
      project-name:
        required: true
        description: "The name of the C# project to validate."
        type: string
      version:
        required: true
        description: The version of the package to check.
        type: string
      cicd-scripts-version:
        required: true
        description: The version of the CICD scripts to use.
        type: string


jobs:
  build_script_url:
    name: Build Script URL
    uses: KinsonDigital/Infrastructure/.github/workflows/create-script-url.yml@v9.1.1
    with:
      project-name: ${{ inputs.project-name }}
      cicd-scripts-version: ${{ inputs.cicd-scripts-version }}


  nuget_pkg_does_not_exist:
    name: Validate NuGet Package Does Not Exist
    runs-on: ubuntu-latest
    needs: build_script_url
    steps:
      - name: Set Up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Package Does Not Exist
        run: |
          $scriptUrl = "${{ needs.build_script_url.outputs.script-url }}/nuget-pkg-does-not-exist.ts";

          <# Deno Args:
            1. PackageName
            2. Version
          #>
          deno run `
            --allow-net `
            "$scriptUrl" `
            "${{ vars.ORGANIZATION_NAME }}.${{ inputs.project-name }}" `
            "${{ inputs.version }}";
