name: ⚙️ Process Milestone


permissions:
  contents: read


defaults:
  run:
    shell: pwsh


on:
  workflow_call:
    inputs:
      owner-name:
        required: true
        description: "The name of the repository owner."
        type: string
      repo-name:
        required: true
        description: "The name of the repository."
        type: string
      version:
        required: true
        description: "The application/library version."
        type: string
    secrets:
      cicd-pat:
        required: true
        description: "The CICD personal access token."


jobs:
  process_milestone:
    name: Process Milestone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          repository: KinsonDigital/Infrastructure
          ref: v17.2.0 # TODO: This needs to be set to the latest tag and should be auto updated with infra releases

      - name: Set Up Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed #v2.0.5
        with:
          deno-version: v2.7.14

      - name: Get Version Type
        id: get-version-type
        env:
          VERSION: "${{ inputs.version }}"
        run: deno run -EN "$env:GITHUB_WORKSPACE/.github/reusable-workflow-scripts/get-version-type.ts";

      - name: Rename Milestone
        if: ${{ steps.get-version-type.outputs.version-type == 'production' }}
        uses: ./actions/rename-milestone
        with:
          owner-name: "${{ inputs.owner-name }}"
          repo-name: "${{ inputs.repo-name }}"
          current-milestone-name: "vnext"
          new-milestone-name: "${{ inputs.version }}"
          github-token: "${{ secrets.cicd-pat }}"

      - name: Close Milestone
        uses: ./actions/close-milestone
        with:
          repo_owner: ${{ inputs.owner-name }}
          repo_name: ${{ inputs.repo-name }}
          milestone-title: "${{ inputs.version }}"
          github-token: "${{ secrets.cicd-pat }}"

      - name: Create New VNext Milestone
        if: ${{ steps.get-version-type.outputs.version-type == 'production' }}
        uses: ./actions/create-milestone
        with:
          repo-owner: "${{ inputs.owner-name }}"
          repo-name: "${{ inputs.repo-name }}"
          milestone-title: "vnext"
          github-token: "${{ secrets.cicd-pat }}"

      - name: Get Next Preview Version
        if: ${{ steps.get-version-type.outputs.version-type == 'preview' }}
        id: get-next-preview-version
        env:
          PREVIEW_VERSION: "${{ inputs.version }}"
        run: deno run -EN "$env:GITHUB_WORKSPACE/.github/reusable-workflow-scripts/get-next-preview-version.ts";

      - name: Create New Preview Milestone
        if: ${{ steps.get-version-type.outputs.version-type == 'preview' }}
        uses: ./actions/create-milestone
        with:
          repo-owner: "${{ inputs.owner-name }}"
          repo-name: "${{ inputs.repo-name }}"
          milestone-title: "${{ steps.get-next-preview-version.outputs.next-preview-version }}"
          github-token: "${{ secrets.cicd-pat }}"
