name: 🚀 Release
run-name: 🚀 ${{ inputs.release-type }} Release ${{ inputs.dry-run == true && '(Dry Run)' || '' }}


permissions:
  contents: read


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:
    inputs:
      release-type:
        required: true
        description: The type of release to validate.  Either 'Preview' or 'Production'.
        type: choice
        options: [Production, Preview]
      dry-run:
        required: false
        description: Dry Run - Check to run the workflow without creating a release.
        default: false
        type: boolean


env:
  OWNER_NAME: "${{ vars.ORGANIZATION_NAME }}"
  REPO_NAME: "${{ vars.PROJECT_NAME }}"


jobs:
  get_and_validate_version:
    name: Get And Validate Version
    runs-on: ubuntu-latest-26.04
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Get Version
        id: get-version
        uses: ./actions/get-version@v16.0.0
        with:
          version-file-path: "${{ github.workspace }}/deno.json"
          deno-version: "${{ vars.DENO_VERSION }}"
          json-prop-path: "version"

      - name: Validate Version
        id: validate-version
        uses: ./actions/validate-version@v16.0.0
        with:
          version: "${{ steps.get-version.outputs.version}}"
          release-type: "${{ inputs.release-type }}"
          deno-version: "${{ vars.DENO_VERSION }}"


  run_prerelease_validation:
    name: Run Pre-Release Validation
    needs: [get_and_validate_version]
    uses: ./.github/workflows/validate-release.yml
    with:
      owner-name: "${{ vars.ORGANIZATION_NAME }}"
      repo-name: "${{ vars.PROJECT_NAME }}"
      version: "${{ needs.get_and_validate_version.outputs.version }}"
      release-type: "${{ inputs.release-type }}"
      relative-release-notes-file-path: "release-notes/${{ inputs.release-type }}-releases/Release-Notes-${{ needs.get_and_validate_version.outputs.version }}.md"
    secrets:
      cicd-pat: ${{ secrets.CICD_TOKEN }}


  build:
    name: Build
    runs-on: ubuntu-latest-26.04
    needs: [get_and_validate_version, run_prerelease_validation]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Set Up Deno (${{ vars.DENO_VERSION }})
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed #v2.0.5
        with:
          deno-version: ${{ vars.DENO_VERSION }}
          cache: true

      - name: Build
        run: deno check ./**/*.ts;


  lint:
    name: Lint
    runs-on: ubuntu-latest-26.04
    needs: [get_and_validate_version, run_prerelease_validation]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Set Up Deno (${{ vars.DENO_VERSION }})
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed #v2.0.5
        with:
          deno-version: ${{ vars.DENO_VERSION }}
          cache: true

      - name: Lint
        run: deno lint "./**/*.ts";


  perform_release:
    name: Perform ${{ inputs.release-type }} Release
    runs-on: ubuntu-latest-26.04
    needs: [get_and_validate_version, run_prerelease_validation, build, lint]
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          token: ${{ secrets.CICD_TOKEN }}

      - name: Set Up Deno (${{ vars.DENO_VERSION }})
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed #v2.0.5
        with:
          deno-version: ${{ vars.DENO_VERSION }}
          cache: true

      - name: Lowercase Release Type
        id: release-type
        run: |
          $releaseType = "${{ inputs.release-type }}".ToLower();
          "release-type=$releaseType" > "$env:GITHUB_OUTPUT";

      - name: Update Reusable Workflow Versions ${{ inputs.dry-run == true && '(Dry Run)' || '' }}
        if: inputs.dry-run == false
        env:
          BASE_DIR_PATH: "${{ github.workspace }}/.github/workflows"
          NEW_VERSION: "${{ needs.get_and_validate_version.outputs.version }}"
          GITHUB_TOKEN: "${{ secrets.CICD_TOKEN }}"
        run: |
          deno run -ERWN "${{ github.workspace }}/.github/internal-cicd/scripts/update-workflow-versions.ts";

          $releaseType = "${{ inputs.release-type }}";

          git config --global user.email "${{ vars.GIT_CONFIG_EMAIL }}";
          git config --global user.name "CICD Release Script - (On behalf of Calvin Wilkinson)";

          git add -A;
          git commit -m "🚀$releaseType (${{ needs.get_and_validate_version.outputs.version }}) - Update reusable workflow versions";
          git push;

      - name: Create GitHub Release ${{ inputs.dry-run == true && '(Dry Run)' || '' }}
        if: inputs.dry-run == false
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          name: "🚀${{ inputs.release-type }} - ${{ needs.get_and_validate_version.outputs.version }}"
          tag: ${{ needs.get_and_validate_version.outputs.version }}
          owner: ${{ env.OWNER_NAME }}
          repo: ${{ env.REPO_NAME }}
          bodyFile: "${{ github.workspace }}/release-notes/${{ steps.release-type.outputs.release-type }}-releases/Release-Notes-${{ needs.get_and_validate_version.outputs.version }}.md"
          prerelease: ${{ inputs.release-type }} == 'Preview'

      - name: Update CICD Script Version Repo Var ${{ inputs.dry-run == true && '(Dry Run)' || '' }}
        env:
          INFRASTRUCTURE_VERSION_REPO_VAR_NAME: "INFRASTRUCTURE_VERSION"
          VERSION: "${{ needs.get_and_validate_version.outputs.version }}"
          GITHUB_TOKEN: "${{ secrets.CICD_TOKEN }}"
        run: |
          if ("${{ inputs.dry-run == true }}" -eq "true") {
            Write-Host "::notice::Updating 'INFRASTRUCTURE_VERSION' repository variable ...";
            exit 0;
          }

          deno run -EN "${{ github.workspace }}/.github/internal-cicd/scripts/update-cicd-script-version.ts";


  process_milestone:
    name: Process Milestone
    needs: [get_and_validate_version, run_prerelease_validation, build, lint, perform_release]
    uses: ./.github/workflows/process-milestone.yml
    with:
      owner-name: "${{ vars.ORGANIZATION_NAME }}"
      repo-name: "${{ vars.PROJECT_NAME }}"
      version: "${{ needs.get_and_validate_version.outputs.version }}"
    secrets:
      cicd-pat: "${{ secrets.CICD_TOKEN }}"
