name: Sync Issue To PR


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    types: opened
  issue_comment: # This event is triggered when created issue and pr comments
    types: created


jobs:
  sync_issue_to_pr:
    name: Start Sync Process
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Sync
        run: |
          $eventName = "${{ github.event_name }}";
          $scriptUrl = "${{ vars.SCRIPT_BASE_URL }}/${{ vars.CICD_SCRIPTS_VERSION }}/${{ vars.SCRIPT_RELATIVE_DIR_PATH}}/sync-issue-to-pr.ts";
          $prNubmer = $eventName -eq "pull_request" ? "${{ github.event.number }}" : "${{ github.event.issue.number }}";
          $command = $eventName -eq "issue_comment" ? "${{ github.event.comment.body }}" : "no comment";
          
          
          echo "Executed By: ${{ github.event.sender.login }}";
          echo "Event Name: $eventName";
          echo "Project Name: ${{ vars.PROJECT_NAME }}";
          echo "PR Number: $prNubmer";
          echo "Comment: ";
          echo "Default PR Reviewer: ${{ vars.DEFAULT_PR_REVIEWER }}";
          echo "Relative PR Sync Template File Path: ${{ vars.RELATIVE_PR_SYNC_TEMPLATE_FILE_PATH }}";

          deno run `
            --allow-net `
            "$scriptUrl" `
            "${{ vars.PROJECT_NAME }}" `
            "$prNubmer" `
            "$command" `
            "${{ vars.DEFAULT_PR_REVIEWER }}" `
            "${{ vars.RELATIVE_PR_SYNC_TEMPLATE_FILE_PATH }}" `
            "${{ secrets.CICD_REST_API }}";
