name: ✔Branch Validator Unit Testing Status Check


on:
  workflow_call:
    inputs:
      projectname:
        required: true
        type: string
      netsdkversion:
        required: true
        type: string
   


jobs:
  Unit_Testing_Status_Check:
    name: Branch Validator Unit Testing Status Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Build Config
      id: get-build-config
      shell: pwsh
      run: |
        # If the destination branch that the pull request is merging into is master, do a release build
        if ( "${{ github.base_ref }}" -eq "master") {
          Write-Host "::set-output name=build-config::Release"
        } else { # Any other branch than master, do a debug build
          Write-Host "::set-output name=build-config::Debug"
        }

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.netsdkversion }}

    - name: Restore Dependencies
      run: dotnet restore "${{ github.workspace }}/${{ inputs.projectname }}/${{ inputs.projectname }}.csproj"

    - name: Execute Unit Tests
      run: dotnet test "${{ github.workspace }}/Testing/${{ inputs.projectname }}Tests/${{ inputs.projectname }}Tests.csproj" `
        -c ${{ steps.get-build-config.outputs.build-config }} `
        --no-restore
