name: ✔Unit Testing Status Check


on:
  workflow_call:
    inputs:
      projectname:
        required: true
        type: string
      buildconfig:
        required: true
        type: string
      netsdkversion:
        required: true
        type: string


jobs:
  Unit_Testing_Status_Check:
    name: Setup .NET SDK
    runs-on: windows-latest # TODO: Turn this into an input but not required and with default value of ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.netsdkversion }}

      - name: Restore Dependencies
        run: dotnet restore "${{ github.workspace }}/Testing/${{ inputs.projectname }}Tests/${{ inputs.projectname }}.csproj"

      - name: Execute Unit Tests
        run: dotnet test "${{ github.workspace }}/Testing/${{ inputs.projectname }}Tests/${{ inputs.projectname }}Tests.csproj" `
          -c ${{ inputs.buildconfig }} `
          --no-restore
