name: Validate Tag


defaults:
  run:
    shell: pwsh


on:
  workflow_call:
    inputs:
      project-name:
        required: true
        description: "The name of the C# project to validate."
        type: string
      release-type:
        required: true
        description: The type of release to validate.  Either 'Preview' or 'Production'.
        type: string
      tag-name:
        required: true
        description: The name of the tag to validate.
        type: string
      cicd-scripts-version:
        required: true
        description: The version of the CICD scripts to use.
        type: string
    secrets:
      cicd-pat:
        required: true
        description: The CICD personal access token.
      
        
jobs:
  validate_workflow_inputs:
    name: Validate Workflow Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Validate Inputs
        run: |
          # Verify that the project name workflow input is not empty
          if ("${{ inputs.project-name }}" -eq "") {
            Write-Host "::error::The 'project-name' workflow input cannot be empty.";
            exit 1;
          }


          $releaseType = "${{ inputs.release-type }}";

          # Verify that the release type is only 'Preview' or 'Production'
          if ($releaseType -ne "Preview" -and $releaseType -ne "Production") {
            Write-Host "::error::The release type '$releaseType' is invalid.  Valid values are 'Preview' or 'Production'.";
            exit 1;
          }


          $tagName = "${{ inputs.tag-name }}";
          $tagNameRegex = "v[0-9]+\.[0-9]+\.[0-9]+";
          
          # Verify that the cicd script version has valid syntax
          if ($tagName -match $tagNameRegex) {
            Write-Host "::notice::The tag name is valid.";
          } else {
            Write-Host "::error::The tag name is not valid.\nThe version format is: 'v#.#.#'";
            exit 1;
          }


          $cicdScriptVersion = "${{ inputs.cicd-scripts-version }}";
          $cicdScriptVersionRegex = "v[0-9]+\.[0-9]+\.[0-9]+";
          
          # Verify that the cicd script version has valid syntax
          if ($cicdScriptVersion -match $cicdScriptVersionRegex) {
            Write-Host "::notice::The cicd script version is valid.";
          } else {
            Write-Host "::error::The cicd script version is not valid.\nThe version format is: 'v#.#.#'";
            exit 1;
          }


  build_script_url:
    name: Build Script URL
    uses: KinsonDigital/Infrastructure/.github/workflows/create-script-url.yml@v9.0.1
    with:
      project-name: ${{ inputs.project-name }}
      cicd-scripts-version: ${{ inputs.cicd-scripts-version }}


  validate_tag:
    name: Validate Tag
    runs-on: ubuntu-latest
    needs: build_script_url
    steps:
      - name: Set Up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Validate Tag
        run: |
          $scriptUrl = "${{ needs.build_script_url.outputs.script-url }}/validate-tag.ts";
        
          <# Deno Args:
            1. Repo Name
            2. Tag Type
            3. Release Type - Either 'Preview' or 'Production'
            3. Tag Name - This is the version
            4. PAT
          #>
          deno run `
            --allow-net `
            "$scriptUrl" `
            "${{ inputs.project-name }}" `
            "${{ inputs.release-type }}" `
            "${{ inputs.tag-name }}" `
            "${{ secrets.cicd-pat }}";
