name: Validate Release Notes


defaults:
  run:
    shell: pwsh


on:
  workflow_call:
    inputs:
      project-name:
        required: true
        description: "The name of the C# project to validate."
        type: string
      version:
        required: true
        description: The version of the milestone to validate.
        type: string
      cicd-scripts-version:
        required: true
        description: The version of the CICD scripts to use.
        type: string
    secrets:
      cicd-pat:
        required: true
        description: The CICD personal access token.
      

jobs:
  build_script_url:
    name: Build Script URL
    uses: KinsonDigital/Infrastructure/.github/workflows/create-script-url.yml@v10.0.0
    with:
      project-name: ${{ inputs.project-name }}
      cicd-scripts-version: ${{ inputs.cicd-scripts-version }}

  validate_milestone_status:
    name: Validate Milestone Status
    runs-on: ubuntu-latest
    needs: build_script_url
    steps:
      - name: Set Up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Milestone Exists
        run: |
          $scriptUrl = "${{ needs.build_script_url.outputs.script-url }}/milestone-exists.ts";

          <# Deno Args:
            1. Project name
            2. Milestone title - This is a prev or prod version
            3. PAT
          #>
          deno run `
            --allow-net `
            "$scriptUrl" `
            "${{ inputs.project-name }}" `
            "${{ inputs.version }}" `
            "${{ secrets.cicd-pat }}";

      - name: Validate Milestone
        run: |
          $scriptUrl = "${{ needs.build_script_url.outputs.script-url }}/milestone-items-all-closed.ts";
        
          <# Deno Args:
            1. Repo name
            2. MilestoneTitle - This is a prev or prod version
            3. PAT
          #>
          deno run `
            --allow-read --allow-net `
            "$scriptUrl" `
            "${{ inputs.project-name }}" `
            "${{ inputs.version }}" `
            "${{ secrets.cicd-pat }}";
