name: Validate Tag


defaults:
  run:
    shell: pwsh


on:
  workflow_call:
    inputs:
      project-name:
        required: true
        description: The name of the C# project to validate
        type: string
      tag-name:
        required: true
        description: The name of the tag to validate
        type: string
      cicd-scripts-version:
        required: true
        description: The version of the CICD scripts to use
        type: string
    secrets:
      cicd-rest-api:
        description: The CICD REST API token
        required: true
      
        
jobs:
  build_script_url:
    name: Build Script URL
    uses: KinsonDigital/Infrastructure/.github/workflows/create-script-url.yml@v5.0.0
    with:
      project-name: ${{ inputs.project-name }}
      cicd-scripts-version: ${{ inputs.cicd-scripts-version }}


  validate_tag:
    name: Validate Tag
    runs-on: ubuntu-latest
    needs: build_script_url
    steps:
      - name: Set Up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Validate Tag
        run: |
          $scriptUrl = "${{ needs.build_script_url.outputs.script-url }}/validate-tag.ts";
        
          <# Deno Args:
            1. RepoName
            2. TagType
            3. TagName - This is the version
            4. Secret
          #>
          deno run `
            --allow-net `
            "$scriptUrl" `
            "${{ inputs.project-name }}" `
            "preview" `
            "${{ inputs.tag-name }}" `
            "${{ secrets.cicd-rest-api }}";
