name: ✅Workflow Version Status Check


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    branches: [main, preview]


jobs:
  workflow_version_status_check:
    name: Workflow Version Status Check
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.ref == vars.PREV_PREP_RELEASE_HEAD_BRANCH ||
            github.event.pull_request.head.ref == vars.PROD_PREP_RELEASE_HEAD_BRANCH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ vars.DENO_VERSION }}

      - name: Run Status Check Script
        env:
          OWNER_NAME: "${{ vars.ORGANIZATION_NAME }}"
          REPO_NAME: "${{ vars.PROJECT_NAME }}"
          BASE_DIR_PATH: "${{ github.workspace }}/.github/workflows"
          GITHUB_TOKEN: "${{ secrets.CICD_TOKEN }}"
        run: deno run -ERN "${{ github.workspace }}/.github/internal-cicd/scripts/workflow-version-status-check.ts";
